stages:
  # - analysis
  - build

variables:
  DOCKER_DRIVER: overlay2
  RUNNER_ID: ${CI_JOB_ID}
  # CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}
  SONAR_SERVER: 'https://sonar-cathay.akachains.io'
  CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}
  IMAGE_NAME: ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}
  GIT_SUBMODULE_STRATEGY: recursive
  REPO_MANIFEST_NAME: explorer
  REPO_MANIFEST_URL: git@gitlab.com:akachain/gitops/explorer.git
  REPO_MANIFEST_BRANCH: master
  REPO_MANIFEST_ENV_DEV: ./clusters/k8s-dev
  REPO_MANIFEST_ENV_QA: ./clusters/k8s-qa
  REPO_MANIFEST_ENV_UAT: ./clusters/k8s-uat
  REPO_MANIFEST_ENV_TEST: ./clusters/k8s-test
  REPO_MANIFEST_TAG_IMAGE: image_cosmos_api

# sonarqube-reports:
#   stage: analysis
#   image: akachain/sonar-runner-typescript:1.1.0
#   tags:
#     - akcCluster
#     - build
#   variables:
#     SONAR_URL: ${SONAR_SERVER}
#     SONAR_ANALYSIS_MODE: publish
#   script:
#     - set -xe
#     - export SONAR_SCANNER_OPTS="-Xmx2048m";
#     - echo ${CI_COMMIT_REF_NAME} && echo ${CI_PROJECT_NAME};
#     - BRANCH=$(echo ${CI_COMMIT_REF_NAME} | sed -r 's/\//\\\//g');
#     - source /tmp/efs-config/deployConfig/env.sh
#     - sed -e "s/%BRANCH%/${BRANCH}/g" -e "s/%SONAR_USER%/${SONAR_USER}/g" -e "s/%SONAR_PASSWORD%/${SONAR_PASSWORD}/g" -e "s/%PROJECT_NAME%/${CI_PROJECT_NAME}/g" sonar-project.properties-template > sonar-project.properties;
#     - cat sonar-project.properties;
#     - gitlab-sonar-scanner

build:
  stage: build
  tags:
    - build
    - akcCluster
  script:
    - chmod 777 -R ./ci
    - ./ci/build.sh
    - ./ci/updateManifest.sh
  only:
    - develop
    - uat
    - qa
    - test
