version: '3.9'
services:
  # api-service:
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - redis
  #     - influxdb
  #   networks:
  #     - dev_network
  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aura_scan_dev
      - MYSQL_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev_network
  adminer:
    image: adminer:4-standalone
    ports:
      - "8080:8080"
    networks:
      - dev_network
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dev_network

volumes:
  db_data:
  redis_data:

networks:
  dev_network:
    driver: bridge
